#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

version=$1

cat > pyproject.toml <<EOF
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dict2cypher"
version = "${version}"
description = "Convert Python dicts to Neo4j Cypher queries easily"
authors = [
    {name = "Norman Koch", email = "norman.koch@tu-dresden.de"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.8"
EOF

exit 0
